{% set name = "cassowary" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7c0d10722738eca3cd939c8f6f1a580fdfa4fad71b71d0d193c10aaa3d406dd

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - cassowary

about:
  home: https://pypi.org/project/cassowary/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Pure Python PNG image encoder/decoder'

extra:
  recipe-maintainers:
    - hmaarrfk
