travis:
  secure:
    BINSTAR_TOKEN: Aaga0+51GjqP8tJma5Gcy1xmqTswuR5BCumLRL/sOYQc994zABYmL0+82cKV25E9XB9WH6kCIBluZsVEYTOMO1rqOOzhzUjViP/klWwHEscMyDGiL1HqsKzkjVpbVIRqgTAB4dlOSr2WPAjexYhl93fjZIokF5PcNXSJZSNAtq/kgf5lh6/KJ6MRMxW9r/0s20zTysrYZ7g6yagIjPyzS7buJEulQ6FjTINuVbSHK6pmBVNt1Oagotb0sbI83dX/9HlI05cJruS/BAaOI539kHsYGAIOVxOWHSdvGEuonCin8EcSvEZ+J0Yow9uOBua0DExjQcyfyjkuD0diHCCDn+5VeVhSvU9+2d5OfuF/+jPTIUtW+qzDAceRn30PgJesbGVdMRsaAQkIO2uRUojbNf9/2fHiwTbbU/+o9aBZu8UuwSPOffG14+GSyX/wyXVKi5zNR392yIouHneO5WHWS83gUgMCis4vvcRp5SmjOxd5sjBjaxXYO+9/NxU1cVjlM1ZemTdu+XUPfelxj5JSAPjW68FYRtvbj+E+ZGyjKqD2aEVoLzDquqScGmMz2sxcrcYlj9Ft69R77V38DyS49wHhHnXM+jqvhx/F91U4JB6WMJqPdOM2t6ekFwpJtjR9QWSYbrbAG9D5qhkKtrgLaGZcaJ3fTfKXqmBbv9ZgZGQ=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
